E-Commerce-MVC/Controllers/OrderController.cs
using E_Commerce_MVC.Controllers;
using E_Commerce_MVC.Models.User;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace E_Commerce_MVC.Models
{
    public class OrderController : Controller
    {
        //Get all order för en spsific user
        public async Task<ActionResult> Index()
        {
            var http = new HttpClient();

            var _orders = await http.GetFromJsonAsync<List<MyOrder>>($"https://localhost:44356/api/Order/UserOrder/{HttpContext.Session.GetString("UserId") }");

            if (_orders.Count > 0)
                return View(_orders);
            else
                return View(null);
        }

        // GET: OrderController/Create
        public async Task<ActionResult> Create()
        {

            var uri = Request.Path.Value;

            if (HttpContext.Session.GetString("UserId") == null)
            {
               // HttpContext.Session.SetString ("Referrer",uri);

                return RedirectToAction("SignIn", "Autentication", new {ReturnUrl = uri });
            }       

            else
            {
                List<SelectListItem> list = new List<SelectListItem>(); //save delivery types

                List<SelectListItem> Addresses = new List<SelectListItem>(); // save user addresses one user can has two addresses
                var http = new HttpClient();

                var _deliveryType = await http.GetFromJsonAsync<List<DeliveryType>>("https://localhost:44356/api/DeliveryType");

                var _address = await http.GetFromJsonAsync<List<UserAddress>>($"https://localhost:44356/api/UserAddress/AllAddress/{HttpContext.Session.GetString("UserId") }");


                foreach (var type in _deliveryType)
                {
                    list.Add(new SelectListItem
                    {
                        Text = type.Name,
                        Value = type.Id.ToString()
                    });

                }

                foreach (var address in _address)
                {
                    Addresses.Add(new SelectListItem
                    {
                        Text = address.Address.AddressLine+address.Address.ZipCode+address.Address.City,
                        Value = address.Id.ToString()
                    });

                }

                ViewData["DeliveryType"] = list;

                ViewData["Addresses"] = Addresses;

                return View();

            }           
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< ActionResult> Create(Order order)
        {
            try
            {
                var _order = new Order
                {
                    OrderDate = order.OrderDate,
                    OurReference = order.OurReference,
                    Status = order.Status,
                    DeliveryAddressId = order.DeliveryAddressId,
                    InvoiceAddressId = order.InvoiceAddressId,
                    UserId = int.Parse(HttpContext.Session.GetString("UserId")),
                    DeliveryTypeId = order.DeliveryTypeId
                };

                var client = new HttpClient();
                var response =  await client.PostAsJsonAsync("https://localhost:44356/api/Order",_order);

                var returnValue = await response.Content.ReadFromJsonAsync<Order>();

                int _orderId = returnValue.Id;

                List<ShoppingCartItem> ShoppingCart = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart");

                foreach ( var item in ShoppingCart)
                {
                    var _orderItem = new OrderItem
                    {
                        OrderId = _orderId,
                        ProductId = item.product.Id,
                        Quantity = item.quantity,
                        UnitPrice = item.product.Price
                    };

                    await client.PostAsJsonAsync("https://localhost:44356/api/OrderItem", _orderItem);

                }

                HttpContext.Session.Remove("Cart");
                HttpContext.Session.Remove("Count");
                HttpContext.Session.Remove("TotalPrice");

            return RedirectToAction("Index" ,"Products");
              
            }
            catch
            {
                return View(order);
            }
        }

        public async Task<ActionResult> Details(int id)
        {
            var http = new HttpClient();

            var _order = await http.GetFromJsonAsync<MyOrder>($"https://localhost:44356/api/Order/{id}");

            return View(_order);

        }


        public async Task<ActionResult> Delete(int id)
        {
            var http = new HttpClient();

             await http.DeleteAsync($"https://localhost:44356/api/Order/{id}");

            return RedirectToAction("Index");

        }
    }
}

E-Commerce-MVC/Controllers/ShoppingCartController.cs
using E_Commerce_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace E_Commerce_MVC.Controllers
{

    public static class SessionExtensions
    {

        public static T GetComplexData<T>(this ISession session, string key)
        {
            var data = session.GetString(key);
            if (data == null)
            {
                return default(T);
            }
            return JsonConvert.DeserializeObject<T>(data);
        }

        public static void SetComplexData(this ISession session, string key, object value)
        {
            session.SetString(key, JsonConvert.SerializeObject(value));
        }
}
public class ShoppingCartController : Controller
    {
       
        public async Task<ActionResult> AddToCart(int id)
        {


            List<ShoppingCartItem> _prevCart = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart"); // My saved shopping cart

            List<ShoppingCartItem> _shoppingCart = new List<ShoppingCartItem>();


            var http = new HttpClient();

            var product = await http.GetFromJsonAsync<Product>($"https://localhost:44356/api/Product/{id}");

            if (_prevCart == null)
            {

                _shoppingCart.Add(new ShoppingCartItem
                {
                    product = product,
                    quantity = 1
                });

                HttpContext.Session.SetComplexData("Cart", _shoppingCart);


            }
            else
            {
                var _product = _prevCart.Find(x => x.product.Id == id);

                if (_product == null) //if  shopping cart doesnot contain the product
                {

                    _prevCart.Add(new ShoppingCartItem
                    {
                        product = product,
                        quantity = 1
                    });


                    HttpContext.Session.Remove("Cart");
                    HttpContext.Session.SetComplexData("Cart", _prevCart);

                }
                else // if  shopping cart contain the product increment quantity
                {
                    int index = _prevCart.IndexOf(_product);
                    _prevCart[index].quantity += 1;


                    HttpContext.Session.Remove("Cart");
                    HttpContext.Session.SetComplexData("Cart", _prevCart);
                }

            }


            HttpContext.Session.SetInt32("Count", Count());
            HttpContext.Session.SetInt32("TotalPrice", TotalPrice());

            return RedirectToAction("Index", "Products");


        }


        public IActionResult ViewCart()
        {
            List<ShoppingCartItem> data = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart");
            return View(data);
        }


        public IActionResult Increment(int id)
        {

            List<ShoppingCartItem> _Cart = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart"); // My saved shopping cart

            var _product = _Cart.Find(x => x.product.Id == id);

            int index = _Cart.IndexOf(_product);

            _Cart[index].quantity += 1;

            HttpContext.Session.Remove("Cart");
            HttpContext.Session.SetComplexData("Cart", _Cart);

            HttpContext.Session.Remove("Count");
            HttpContext.Session.SetInt32("Count", Count());


            HttpContext.Session.Remove("TotalPrice");
            HttpContext.Session.SetInt32("TotalPrice", TotalPrice());


            return RedirectToAction("ViewCart",_Cart);
        }


        public IActionResult Decrement(int id)
        {

            List<ShoppingCartItem> _Cart = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart"); // My saved shopping cart

            var _product = _Cart.Find(x => x.product.Id == id);

            int index = _Cart.IndexOf(_product);

            if (_Cart[index].quantity > 1)
                _Cart[index].quantity -= 1;


            else
                _Cart.RemoveAt(index);

            //Check if the shopping cart is empty

            if(_Cart.Count>0)
            {
                HttpContext.Session.Remove("Cart");
                HttpContext.Session.SetComplexData("Cart", _Cart);

                HttpContext.Session.Remove("Count");
                HttpContext.Session.SetInt32("Count", Count());

                HttpContext.Session.Remove("TotalPrice");
                HttpContext.Session.SetInt32("TotalPrice", TotalPrice());

            }
            else
            {
                HttpContext.Session.Remove("Cart");
                HttpContext.Session.Remove("Count");
                HttpContext.Session.Remove("TotalPrice");
            }

            return RedirectToAction("ViewCart", _Cart);
        }

        public IActionResult Remove(int id)
        {

            List<ShoppingCartItem> _Cart = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart"); // My saved shopping cart

            var _product = _Cart.Find(x => x.product.Id == id);

            int index = _Cart.IndexOf(_product);

             _Cart.RemoveAt(index);

            HttpContext.Session.Remove("Cart");
            HttpContext.Session.SetComplexData("Cart", _Cart);

            HttpContext.Session.Remove("Count");
            HttpContext.Session.SetInt32("Count", Count());


            HttpContext.Session.Remove("TotalPrice");
            HttpContext.Session.SetInt32("TotalPrice", TotalPrice());

            return RedirectToAction("ViewCart", _Cart);
        }




        public int Count()
        {
            int count = 0;
            List<ShoppingCartItem> data = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart");
            foreach (var item in data)
            {
                count = count + item.quantity;

            }


            return count;
        }


        public int TotalPrice()
        {
            int total = 0;
            List<ShoppingCartItem> data = HttpContext.Session.GetComplexData<List<ShoppingCartItem>>("Cart");
            foreach (var item in data)
            {
                total = total + Convert.ToInt32(item.product.Price * item.quantity);

            }


            return total;
        }


    }
}

E-Commerce-MVC/Views/Shared/_FooterPartial.cshtml
<footer class="border-top footer text-white py-3 bg-secondary mt-5">
    <div class="container text-center">
        &copy; 2021 - e-Furniture- <a asp-area="" asp-controller="Home" asp-action="Index" class="text-white ms-3">Home</a>
    </div>
</footer>

E-Commerce-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Hans Mattin-Lassei, EPN Sverige AB">
    <title>@ViewData["Title"] -E-Möbler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/124ac6c2b5.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="bg-light page-container">

    @await Html.PartialAsync("_NavbarPartial")

    @*Serach product with name   *@

    @await Html.PartialAsync("_SearchPartial")

    <div>
        @RenderBody()
    </div>


    @await Html.PartialAsync("_FooterPartial")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

E-Commerce-MVC/Views/Shared/_NavbarPartial.cshtml
@using E_Commerce_MVC.Models
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<nav class="navbar navbar-expand-lg navbar-light bg-secondary shadow py-3">
    <div class="container">
        <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index">e-Furniture</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav  ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class=" me-5 text-white text-decoration-none"  asp-controller="Products" asp-action="Index"><i class="fab fa-product-hunt"></i> Products</a>
                </li>

                <li class="nav-item">
                    <a class="text-white text-decoration-none  me-5 position-relative " asp-controller="ShoppingCart" asp-action="ViewCart">
                        <i class="fas fa-cart-plus me-1 "></i>Cart
                        @if (@HttpContextAccessor.HttpContext.Session.GetInt32("Count")!= 0)
                        {
                          <span class="text-light position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">@HttpContextAccessor.HttpContext.Session.GetInt32("Count")</span>
                        }
                    </a>
                   

                </li>



                @*User profile section*@
            <li >

                @if (@HttpContextAccessor.HttpContext.Session.GetString("UserId") == null)
                {
                    <a class="me-5 text-white text-decoration-none" asp-controller="Autentication" asp-action="SignIn"> <i class="fas fa-user"></i> Sign In</a>

                }
                else
                {

                    <div class="dropdown">
                        <a class=" dropdown-toggle me-5 text-white text-decoration-none"  id="user" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-check"></i>  @HttpContextAccessor.HttpContext.Session.GetString("UserName")
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="user">
                            <li><a class="dropdown-item" asp-controller="Autentication" asp-action="SignOut">Sign out</a></li>
                            <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">My order</a></li>
                            <li><a class="dropdown-item" asp-controller="User" asp-action="GetAddress">User Address</a></li>
                            <li><a class="dropdown-item" asp-controller="User" asp-action="ChangePassword">Settings</a></li>



                        </ul>
                    </div>
                    
                }

            </li>
            <li>
                <a class="text-white text-decoration-none"  asp-controller="Autentication" asp-action="SignUp" ><i class="fas fa-user-plus"></i> Sign Up</a>
            </li>


                </ul>

        </div>


        @* <a data-toggle="dropdown" class="dropdown-toggle me-3">
             <i class="fas fa-cart-plus"></i>
            <ul class="dropdown-menu">
                 @if (@ViewData["Cart"] != null)
                 {
                     @foreach (var item in (List<ShoppingCartItem>)ViewData["Cart"])

                     {
                         <li> <a href="#"> @item.product.Name</a></li>
                     }
                 }
             </ul>


                </a>
                </li>

                </ul>*@



    </div>

</nav>

E-Commerce-MVC/Views/Shared/_SearchPartial.cshtml
<div class="container mt-3">
    <form class="d-flex input-group-append" asp-controller="Products" asp-action="Filter" style="padding-right: 25px;">
        <input name="Query" type="text" class="form-control" placeholder="Search for a product..." aria-describedby="button-addon2">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
</div>