E-Commerce-MVC/Models/User/SignUp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_MVC.Models.User
{
    public class SignUp
    {

        [Display(Name = "First name")]
        [Required(ErrorMessage = "{0} must be provided")]
        [StringLength(255, ErrorMessage = "{0} must be at least {2} characters long", MinimumLength = 2)]
        public string FirstName { get; set; }

        [Display(Name = "Last name")]
        [Required(ErrorMessage = "{0} must be provided")]
        [StringLength(255, ErrorMessage = "{0} must be at least {2} characters long", MinimumLength = 2)]
        public string LastName { get; set; }

        [Display(Name = "Email address")]
        [EmailAddress]
        [Required(ErrorMessage = "{0} must be provided")]
        [RegularExpression("^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$", ErrorMessage = "{0} must be a valid address")]
        public string Email { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "{0} must be provided")]
        [RegularExpression(@"^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!*@#$%^&+=]).*$", ErrorMessage = "{0} must be at least 8 characters long, contain one number and a mixture of uppercase and lowercase letters and at least one special character (!*@#$%^&+=)")]
        public string Password { get; set; }

        public AddressModel address { get; set; }
    }
}

E-Commerce-MVC/Controllers/AutenticationController.cs
using E_Commerce_MVC.Models;
using E_Commerce_MVC.Models.User;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace E_Commerce_MVC.Controllers
{
    public class AutenticationController : Controller
    {


        [HttpGet]
        public ActionResult SignIn()
        {
            
            return View();
        }

      [HttpPost]
        public async Task<ActionResult> SignIn(LogIn model,string ReturnUrl)
        {
            var http = new HttpClient();
           
             var result = await http.PostAsJsonAsync("https://localhost:44356/api/User/LogIn", model);

          

            if (result.IsSuccessStatusCode)
            {
                var returnValue = await result.Content.ReadFromJsonAsync<UserModel>();
                HttpContext.Session.SetString("UserId", returnValue.Id.ToString());
                HttpContext.Session.SetString("UserName", returnValue.FirstName.ToString() + " " + returnValue.LastName.ToString());

                if (!string.IsNullOrEmpty(ReturnUrl))
                {
                    /*var url = HttpContext.Session.GetString("Referrer");
                    HttpContext.Session.Remove("Referrer");*/

                    return Redirect(ReturnUrl);

                }

                return RedirectToAction("Index", "Products");

            }
            else
            {
                ViewData["error"] = "the email or password is wrong";
                return View();
            }          
            
        }


        #region SignUp

        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SignUp(SignUp model)
        {
            var http = new HttpClient();
            

            var result = await http.PostAsJsonAsync("https://localhost:44356/api/User/Register", model);

            if (result.IsSuccessStatusCode)
            {
                var returnValue = await result.Content.ReadFromJsonAsync<UserModel>();
                HttpContext.Session.SetString("UserId", returnValue.Id.ToString());
                HttpContext.Session.SetString("UserName", returnValue.FirstName.ToString() + " " + returnValue.LastName.ToString());

                // user address

                var address = new AddressModel
                {
                    AddressLine = model.address.AddressLine,
                    ZipCode = model.address.ZipCode,
                    City = model.address.City
                };

                var _addressRes = await http.PostAsJsonAsync("https://localhost:44356/api/Address", address);
                var _address = await _addressRes.Content.ReadFromJsonAsync<AddressModel>();
                await http.PostAsJsonAsync("https://localhost:44356/api/UserAddress",
                   new UserAddress
                    {
                        UserId = returnValue.Id,
                        AddressId = _address.Id
                    });

                return RedirectToAction("Index", "Products");
            }


            else
            {
                ViewData["error"] = "The Email is already existed";
                return View();
            }


        }
        #endregion


        public ActionResult SignOut()
        {
            HttpContext.Session.Remove("UserId");
            return RedirectToAction("Index", "Products");
        }



    }
}

E-Commerce-MVC/Views/Autentication/SignIn.cshtml
@model E_Commerce_MVC.Models.User.LogIn

@{
    ViewData["Title"] = "SignIn";
}

@{
    var returnUrl = Context.Request.Query["ReturnUrl"];
}

<div class="row d-flex justify-content-center mt-5">

    <div class="col-md-4 border p-5 bg-white shadow-lg mt-5">
        <h1 class="text-center py-5 text-style text-primary"> SIGN IN </h1>
        <form asp-controller="Autentication" asp-action="SignIn" asp-route-returnurl = "@returnUrl" method = "post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="Email" class="form-control mt-2" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group mt-5">
                <label asp-for="password" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="password" class="form-control mt-2" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group mt-5 ">
                <input type="submit" value="Sign in" class="btn btn-primary form-control" />
            </div>

            @if (ViewData["error"] != null)
            {
                <p class="text-danger"> @ViewData["error"]</p>
            }

            <div class="text-center py-3"> New User <a class=" text-primary text-decoration-none" asp-controller="Autentication" asp-action="SignUp"> Register here </a></div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Commerce-MVC/Views/Autentication/SignUp.cshtml
@model E_Commerce_MVC.Models.User.SignUp



@{
    ViewData["Title"] = "SignUp";
}



<div class="row d-flex justify-content-center mt-5">

    <div class="col-md-4 border p-5 bg-white shadow-lg">
        <h1 class="text-center py-5 text-style text-primary"> SIGN IN </h1>
        <form asp-action="SignUp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label fw-bold"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <h4 class="mt-5 text-primary"> User Address </h4>


            <div class="form-group">
                <label asp-for="address.AddressLine" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="address.AddressLine" class="form-control" />
                <span asp-validation-for="address.AddressLine" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="address.ZipCode" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="address.ZipCode" class="form-control" />
                <span asp-validation-for="address.ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.City" class="control-label fw-bold"></label><i class="text-danger fas fa-star"></i>
                <input asp-for="address.City" class="form-control" />
                <span asp-validation-for="address.City" class="text-danger"></span>
            </div>

            @if (ViewData["error"] != null)
            {
                <p class="text-danger"> @ViewData["error"]</p>
            }
            <div class="form-group py-5">
                <input type="submit" value="Sign Up" class="btn btn-primary form-control" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}